[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC Plugin for swc-magic"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_swc_magic"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]


swc_magic = { path = "./transform" }
