[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC Plugin for swc-magic"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_swc_magic"
publish = false
version = "0.5.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1.0.107"
swc_core = { version = "0.88.0", features = ["ecma_plugin_transform"] }


swc_magic = { path = "./transform" }
