[package]

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "remove_assert"
publish      = false
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde            = { workspace = true }
swc_atoms        = { workspace = true }
swc_common       = { workspace = true }
swc_ecma_ast     = { workspace = true }
swc_ecma_visit   = { workspace = true }

[dev-dependencies]
swc_ecma_parser              = { workspace = true }
swc_ecma_transforms_testing  = { workspace = true }
testing                      = { workspace = true }
