[package]

description = "AST Transforms for realy"


name = "swc_relay"
repository = "https://github.com/swc-project/plugins.git"
version = "0.44.5"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
regex = "1.5"
serde = "1"
serde_json = "1"
swc_atoms = "0.6.5"
swc_common = { version = "0.33.19", features = ["concurrent"] }
swc_ecma_ast = "0.112.5"
swc_ecma_utils = "0.127.12"
swc_ecma_visit = "0.98.6"
tracing = { version = "0.1.37" }

[dev-dependencies]
swc_ecma_transforms_testing = "0.140.15"
testing = "0.35.20"
