[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST Transforms for realy"
edition = "2021"
license = "Apache-2.0"
name = "swc_relay"
repository = "https://github.com/swc-project/plugins.git"
version = "0.38.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
regex = "1.5"
serde = "1"
serde_json = "1"
swc_atoms = "0.6.5"
swc_common = { version = "0.33.12", features = ["concurrent"] }
swc_ecma_ast = "0.110.15"
swc_ecma_utils = "0.125.0"
swc_ecma_visit = "0.96.15"
tracing = { version = "0.1.37" }

[dev-dependencies]
swc_ecma_transforms_testing = "0.138.1"
testing = "0.35.14"
