[package]

description = "AST Transforms for realy"


name = "swc_relay"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.44.15"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell      = "1.19.0"
regex          = "1.10"
serde          = "1"
serde_json     = "1"
swc_atoms      = "0.6.7"
swc_common     = { version = "0.33.26", features = ["concurrent"] }
swc_ecma_ast   = "0.113.7"
swc_ecma_utils = "0.128.3"
swc_ecma_visit = "0.99.1"
tracing        = { version = "0.1.40" }

[dev-dependencies]
swc_ecma_transforms_testing = "0.141.1"
testing                     = "0.35.25"
