[package]

description = "AST Transforms for import modularizer"


name = "modularize_imports"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.68.19"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case   = "0.6.0"
handlebars     = "5.1.2"
once_cell      = "1.19.0"
regex          = "1.10"
serde          = "1"
swc_atoms      = "0.6.7"
swc_cached     = "0.3.20"
swc_common     = "0.36.0"
swc_ecma_ast   = "0.117.0"
swc_ecma_visit = "0.103.1"

[dev-dependencies]
swc_ecma_parser             = "0.148.0"
swc_ecma_transforms_testing = "0.146.0"
testing                     = "0.38.0"
