[package]

description = "AST Transforms for import modularizer"


name = "modularize_imports"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.71.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case   = { workspace = true }
handlebars     = { workspace = true }
once_cell      = { workspace = true }
regex          = { workspace = true }
serde          = { workspace = true }
swc_atoms      = { workspace = true }
swc_cached     = { workspace = true }
swc_common     = { workspace = true }
swc_ecma_ast   = { workspace = true }
swc_ecma_visit = { workspace = true }

[dev-dependencies]
swc_ecma_parser             = { workspace = true }
swc_ecma_transforms_testing = { workspace = true }
testing                     = { workspace = true }
