[package]

description = "SWC Plugin for swc-confidential"


authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_plugin_swc_confidential"
publish      = false
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.7.4"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1.0.107"
swc_core   = { version = "0.92.0", features = ["ecma_plugin_transform"] }


swc_confidential = { path = "./transform" }
