[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC plugin for optimization"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_constify"
publish = false
version = "0.5.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_common = { version = "0.33.14", features = ["concurrent"] }
swc_constify = { path = "./transform" }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
swc_ecma_visit = "0.97.0"
swc_ecma_utils = "0.126.0"
swc_ecma_ast = "0.111.0"
swc_plugin_macro = "0.9.16"
