[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "SWC plugin for optimization"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_constify"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_common = { version = "0.32.0", features = ["concurrent"] }
swc_core = { version = "0.81.5", features = [
    "ecma_plugin_transform",
    "ecma_utils",
    "ecma_visit",
    "ecma_ast",
    "common",
] }
swc_constify = { path = "./transform" }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
