[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST Transforms for import modularizer"
edition = "2021"
license = "Apache-2.0"
name = "remove_console"
repository = "https://github.com/swc-project/plugins.git"
version = "0.25.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
swc_atoms = "0.6.5"
swc_cached = "0.3.19"
swc_common = "0.33.16"
swc_ecma_ast = "0.112.0"
swc_ecma_visit = "0.98.0"

[dev-dependencies]
swc_ecma_parser = "0.143.0"
swc_ecma_transforms_base = "0.137.0"
swc_ecma_transforms_testing = "0.140.0"
testing = "0.35.17"
