[package]

description = "AST transforms visitor for swc-magic"


authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_magic"
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.19.7"


[dependencies]
serde          = { version = "1.0.189", features = ["derive"] }
swc_atoms      = "0.6.7"
swc_common     = "0.33.25"
swc_ecma_ast   = "0.113.0"
swc_ecma_utils = "0.128.0"
swc_ecma_visit = "0.99.0"

[dev-dependencies]
swc_ecma_parser             = "0.144.0"
swc_ecma_transforms_base    = "0.138.0"
swc_ecma_transforms_testing = "0.141.0"
testing                     = "0.35.23"
