[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST transforms visitor for swc-magic"
edition = "2021"
license = "Apache-2.0"
name = "swc_magic"
version = "0.1.0"

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
swc_atoms = "0.6.0"
swc_common = "0.33.1"
swc_ecma_ast = "0.110.1"
swc_ecma_utils = "0.124.8"
swc_ecma_visit = "0.96.1"
