[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST transforms visitor for swc-magic"
edition = "2021"
license = "Apache-2.0"
name = "swc_magic"
version = "0.17.0"

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
swc_atoms = "0.6.5"
swc_common = "0.33.14"
swc_ecma_ast = "0.111.0"
swc_ecma_utils = "0.126.0"
swc_ecma_visit = "0.97.0"

[dev-dependencies]
swc_ecma_parser = "0.142.0"
swc_ecma_transforms_base = "0.136.0"
swc_ecma_transforms_testing = "0.139.0"
testing = "0.35.15"
