[package]

description = "AST Transforms for prefresh plugin"

name = "swc_prefresh"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.1.1"

[dependencies]
serde          = { version = "1", features = ["derive"] }
swc_atoms      = "0.6.7"
swc_common     = "0.36.0"
swc_core       = { version = "0.99.0", features = ["ecma_quote"] }
swc_ecma_ast   = "0.117.0"
swc_ecma_visit = "0.103.0"

[dev-dependencies]
swc_ecma_parser             = "0.148.0"
swc_ecma_transforms_base    = "0.143.0"
swc_ecma_transforms_testing = "0.146.0"
testing                     = "0.38.0"
