[package]
authors.workspace      = true
description            = "AST Transforms for emotion"
edition.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "swc_emotion"
repository.workspace   = true
rust-version.workspace = true
version                = "0.72.6"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64           = "0.13"
byteorder        = "1"
fxhash           = "0.2.1"
once_cell        = "1.13.0"
radix_fmt        = "1"
regex            = "1.5"
serde            = "1"
sourcemap        = "6.0.1"
swc_atoms        = "0.6.5"
swc_common       = "0.33.19"
swc_ecma_ast     = "0.112.5"
swc_ecma_codegen = "0.148.11"
swc_ecma_utils   = "0.127.12"
swc_ecma_visit   = "0.98.6"
swc_trace_macro  = "0.1.3"
tracing          = { version = "0.1.37" }

[dev-dependencies]
serde_json                  = "1"
swc_ecma_parser             = "0.143.9"
swc_ecma_transforms_react   = "0.183.16"
swc_ecma_transforms_testing = "0.140.15"
testing                     = "0.35.20"
