[package]
authors      = { workspace = true }
description  = "AST Transforms for emotion"
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_emotion"
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.72.16"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64           = "0.22"
byteorder        = "1"
fxhash           = "0.2.1"
once_cell        = "1.19.0"
radix_fmt        = "1"
regex            = "1.10"
serde            = "1"
sourcemap        = "8.0.1"
swc_atoms        = "0.6.7"
swc_common       = "0.36.0"
swc_ecma_ast     = "0.117.0"
swc_ecma_codegen = "0.154.0"
swc_ecma_utils   = "0.133.0"
swc_ecma_visit   = "0.103.0"
swc_trace_macro  = "0.1.3"
tracing          = { version = "0.1.40" }

[dev-dependencies]
serde_json                  = "1"
swc_ecma_parser             = "0.148.0"
swc_ecma_transforms_react   = "0.189.0"
swc_ecma_transforms_testing = "0.146.0"
testing                     = "0.38.0"
