[package]
authors      = { workspace = true }
description  = "AST Transforms for emotion"
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_emotion"
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.72.18"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64           = "0.22"
byteorder        = "1"
fxhash           = "0.2.1"
once_cell        = "1.19.0"
radix_fmt        = "1"
regex            = "1.10"
serde            = "1"
sourcemap        = "9.0.0"
swc_atoms        = "0.6.7"
swc_common       = "0.37.0"
swc_ecma_ast     = "0.118.0"
swc_ecma_codegen = "0.155.0"
swc_ecma_utils   = "0.134.0"
swc_ecma_visit   = "0.104.0"
swc_trace_macro  = "0.1.3"
tracing          = { version = "0.1.40" }

[dev-dependencies]
serde_json                  = "1"
swc_ecma_parser             = "0.149.0"
swc_ecma_transforms_react   = "0.190.0"
swc_ecma_transforms_testing = "0.147.0"
testing                     = "0.39.0"
