[package]
authors      = { workspace = true }
description  = "AST Transforms for emotion"
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_emotion"
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.104.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64              = { workspace = true }
byteorder           = { workspace = true }
bytes-str           = { workspace = true }
once_cell           = { workspace = true }
radix_fmt           = { workspace = true }
regex               = { workspace = true }
rustc-hash          = { workspace = true }
serde               = { workspace = true }
swc_atoms           = { workspace = true }
swc_common          = { workspace = true }
swc_ecma_ast        = { workspace = true }
swc_ecma_codegen    = { workspace = true }
swc_ecma_transforms = { workspace = true }
swc_ecma_utils      = { workspace = true }
swc_ecma_visit      = { workspace = true }
swc_sourcemap       = { workspace = true }
swc_trace_macro     = { workspace = true }
tracing             = { workspace = true }

[dev-dependencies]
serde_json                  = { workspace = true }
swc_ecma_parser             = { workspace = true }
swc_ecma_transforms_react   = { workspace = true }
swc_ecma_transforms_testing = { workspace = true }
testing                     = { workspace = true }
