[package]

description = "AST Transforms for import modularizer"


name = "react_remove_properties"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.24.14"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde          = { version = "1", features = ["derive"] }
swc_atoms      = "0.6.7"
swc_cached     = "0.3.20"
swc_common     = "0.34.3"
swc_ecma_ast   = "0.115.1"
swc_ecma_visit = "0.101.0"

[dev-dependencies]
swc_ecma_parser             = "0.146.7"
swc_ecma_transforms_base    = "0.140.1"
swc_ecma_transforms_testing = "0.143.1"
testing                     = "0.36.0"
