[package]
authors = ["강동윤 <kdy1997.dev@gmail.com>"]
description = "AST Transforms for import modularizer"
edition = "2021"
license = "Apache-2.0"
name = "react_remove_properties"
repository = "https://github.com/swc-project/plugins.git"
version = "0.9.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
swc_atoms = "0.6.0"
swc_cached = "0.3.17"
swc_common = "0.33.0"
swc_ecma_ast = "0.110.0"
swc_ecma_visit = "0.96.0"

[dev-dependencies]
swc_ecma_parser = "0.141.1"
swc_ecma_transforms_base = "0.134.4"
swc_ecma_transforms_testing = "0.137.4"
testing = "0.35.0"
