[package]

description = "AST Transforms for import modularizer"


name = "react_remove_properties"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.24.17"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde          = { version = "1", features = ["derive"] }
swc_atoms      = "0.6.7"
swc_cached     = "0.3.20"
swc_common     = "0.37.3"
swc_ecma_ast   = "0.118.1"
swc_ecma_visit = "0.104.5"

[dev-dependencies]
swc_ecma_parser             = "0.149.0"
swc_ecma_transforms_base    = "0.144.0"
swc_ecma_transforms_testing = "0.147.0"
testing                     = "0.39.0"
