[package]

description = "AST Transforms for import modularizer"


name = "react_remove_properties"

authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.24.5"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde          = { version = "1", features = ["derive"] }
swc_atoms      = "0.6.5"
swc_cached     = "0.3.19"
swc_common     = "0.33.19"
swc_ecma_ast   = "0.112.5"
swc_ecma_visit = "0.98.6"

[dev-dependencies]
swc_ecma_parser             = "0.143.9"
swc_ecma_transforms_base    = "0.137.15"
swc_ecma_transforms_testing = "0.140.15"
testing                     = "0.35.20"
