[package]

description = "SWC Plugin for swc-magic"


authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_plugin_debug_jsx"
publish      = false
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.1.0"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1.0.107"
swc_core   = { version = "0.90.26", features = ["ecma_plugin_transform"] }


debug_jsx = { path = "./transform" }
