[alias]
xtask = "run --package xtask --"


[build]

rustdocflags = []

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+sse2"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+sse2"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+sse2"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+sse2"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker    = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=-crt-static", "-C", "link-arg=-lgcc"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# We have not adapt this cfg for swc_ecma_minifier, which styled_jsx depends on.
# So we have to manually enable it for all crates except styled jsx.
# [target.'cfg(target_arch = "wasm32")']
# rustflags = [
#   "--cfg=swc_ast_unknown"
# ]
