[package]

description = "AST transforms visitor for swc-confidential"


authors      = { workspace = true }
edition      = { workspace = true }
homepage     = { workspace = true }
license      = { workspace = true }
name         = "swc_confidential"
repository   = { workspace = true }
rust-version = { workspace = true }
version      = "0.19.16"


[dependencies]
cipher         = "0.4.4"
hex            = "0.4.3"
magic-crypt    = "3.1.13"
serde          = { version = "1.0.201", features = ["derive"] }
swc_atoms      = "0.6.7"
swc_common     = "0.37.0"
swc_ecma_ast   = "0.118.0"
swc_ecma_utils = "0.134.0"
swc_ecma_visit = "0.104.0"

[dev-dependencies]
swc_ecma_parser             = "0.149.0"
swc_ecma_transforms_base    = "0.144.0"
swc_ecma_transforms_testing = "0.147.0"
testing                     = "0.39.0"
